### ISSUE TITLE
how to make mplayer persistent for internet audio streams

### ISSUE THREAD

**Issue by peterbmckinley** [philipl/mplayer#1]
Hi, I'm guessing there's a switch for this but here goes. I use mplayer to play HQ 320kbps audio streams (internet radio station URLs, via WiFi).

However if the WiFi is interrupted the stream does not restore automatically and I have to reboot the device to reload the stream (mplayer is set to autorun at boot).

Is there a way to make internet audio streams persistent, i.e. to reconnect and continue playing automatically when WiFi is interrupted and restored? I prefer to turn WiFi off at night and also to leave the device on (Orange Pi Zero)

**Comment by philipl** [comment]
Questions about using mplayer should go to the mplayer-users mailing list: http://www.mplayerhq.hu/design7/mailing_lists.html
