### ISSUE TITLE
how to synchronize the delay of the same audio stream (icecast) on different devices (Raspberry pi3)

### ISSUE THREAD

**Issue by chicco64** [philipl/mplayer#2]
Hi !
I have installed mplayer on two different Raspberry pi3 with the same characteristics.
I need to reproduce a single audio stream coming from an icecast2 server, and I would like to keep, as far as possible, the same "delay" in the audio on these devices, that is, I would like to "synchronize" the audio output of the two raspberry devices.
When mplayer is started (at the same time) on the two Raspberry, the output audio is perfectly synchronized, ie it has the same delay; but, after a few hours, due to the buffer effect, the audio signal are no longer synchronized with each other, even for a few seconds.
To synchronize the two audio signals again, mplayer must be restarted.

"mplayer -cache 320 -cache-min 30 -ao alsa:device=hw=1,0 $SERVER:$PORT/$MOUNT"

Is it possible to periodically delete the buffer on the two raspberry in order to improve synchronization?
I hope for your help !

**Comment by philipl** [comment]
Questions about using mplayer should go to the mplayer-users mailing list: http://www.mplayerhq.hu/design7/mailing_lists.html
